project_id = "sgcaqrtnxqhrrqzxmupa"

[functions.event-processor]
verify_jwt = false

[functions.event-query]
verify_jwt = true

[functions.event-replay]
verify_jwt = true

[functions.get-auth-config]
verify_jwt = false

[functions.enhance-fundraiser-text]
verify_jwt = true
