project_id = "sgcaqrtnxqhrrqzxmupa"

[functions.create-payment-intent]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.search-api]
verify_jwt = false

[functions.event-processor]
verify_jwt = false

[functions.campaign-processor]
verify_jwt = false

[functions.event-query]
verify_jwt = true

[functions.event-replay]
verify_jwt = true

[functions.get-auth-config]
verify_jwt = false

[functions.enhance-fundraiser-text]
verify_jwt = true

[functions.campaign-create]
verify_jwt = true

[functions.campaign-access]
verify_jwt = false

[functions.campaign-rotate-link]
verify_jwt = true

[functions.enhance-project-update]
verify_jwt = true
